# Generated by Django 4.2.11 on 2025-04-02 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocument",
            name="author",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("report", "Report"),
                    ("invoice", "Invoice"),
                    ("proposal", "Proposal"),
                    ("notes", "Notes"),
                ],
                default="notes",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
