# Generated by Django 4.2.11 on 2025-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_projectdocument_author_projectdocument_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocument",
            name="tags",
            field=models.TextField(blank=True, default=""),
        ),
    ]
