# Generated by Django 4.2.11 on 2025-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_projectdocument_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
